name: Open new issue
on: workflow_dispatch

jobs:
  open-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - run: |
          gh issue --repo ${{ github.repository }} \
            create --title "Issue title" --body "Issue body"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

<distributionManagement>
   <repository>
     <id>github</id>
     <name>GitHub ribeiroednilson123/ Apache Maven Packages</name>
     <url>https://maven.pkg.github.com/ribeiroednilson123/Labore.com</url>
   </repository>
</distributionManagement>
