name: Jekyll site CI

on: labore.com
  push:
    branches: [ "principal" ]
  pull_request:
    branches: [ "principal" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \ -v /home/runner/work/labore.com:/srv/jekyll/_site -v /home/runner/work/labore.com/labore.com:/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
